# Generated by Django 5.0.6 on 2025-05-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_alter_recipe_cook_time_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'default_related_name': '%(class)ss', 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Ингредиент для рецепта', 'verbose_name_plural': 'Ингредиенты для рецепта'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'Корзина покупок', 'verbose_name_plural': 'Корзина покупок'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('Гр', 'Граммы'), ('Кг', 'Килограммы'), ('Мл', 'Миллилитры'), ('Л', 'Литр'), ('Шт', 'Штуки'), ('СЛ', 'Столовая ложка'), ('ЧЛ', 'Чайная ложка')], max_length=64, unique=True, verbose_name='Единица измерения'),
        ),
    ]
