# Generated by Django 5.0.6 on 2025-05-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_alter_recipe_cook_time_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='measurement_unit',
        ),
    ]
