# Generated by Django 3.2.16 on 2025-05-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0012_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('Гр', 'Граммы'), ('Кг', 'Килограммы'), ('Мл', 'Миллилитры'), ('Л', 'Литры'), ('Шт', 'Штуки'), ('СЛ', 'Столовые ложки'), ('ЧЛ', 'Чайные ложки')], max_length=64, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название ингредиента'),
        ),
    ]
