# Generated by Django 4.2.21 on 2025-06-04 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(flags=0, message='Недопустимые символы.', regex="^[a-zA-Zа-яА-ЯёЁ\\s\\'-]+$")], verbose_name='Название ингредиента'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=256, validators=[django.core.validators.RegexValidator(flags=0, message='Недопустимые символы.', regex="^[a-zA-Zа-яА-ЯёЁ\\s\\'-]+$")], verbose_name='Название рецепта'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(flags=0, message='Недопустимые символы.', regex="^[a-zA-Zа-яА-ЯёЁ\\s\\'-]+$")], verbose_name='Название'),
        ),
    ]
