# Generated by Django 4.2.21 on 2025-06-04 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(flags=0, message='Недопустимые символы.', regex="^[a-zA-Zа-яА-ЯёЁ\\s\\'-]+$")], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(flags=0, message='Недопустимые символы.', regex="^[a-zA-Zа-яА-ЯёЁ\\s\\'-]+$")], verbose_name='Фамилия'),
        ),
    ]
